export const HOME_TRAN_FETCH_SUCCESS = 'HOME_TRAN_FETCH_SUCCESS';
export const HOME_TRAN_FETCH_FAILURE = 'HOME_TRAN_FETCH_FAILURE';
export const HOME_TRAN_FETCH_REQUEST = 'HOME_TRAN_FETCH_REQUEST';

export const HOME_TRAN_EDIT_REQUEST = 'HOME_TRAN_EDIT_REQUEST';
export const HOME_TRAN_EDIT_SUCCESS = 'HOME_TRAN_EDIT_SUCCESS';
export const HOME_TRAN_EDIT_FAILURE = 'HOME_TRAN_EDIT_FAILURE';

export const HOME_TRAN_DELETE_REQUEST = 'HOME_TRAN_DELETE_REQUEST';
export const HOME_TRAN_DELETE_SUCCESS = 'HOME_TRAN_DELETE_SUCCESS';
export const HOME_TRAN_DELETE_FAILURE = 'HOME_TRAN_DELETE_FAILURE';