export const TRANSACTION_CREATE_SUCCESS = 'TRANSACTION_CREATE_SUCCESS';
export const TRANSACTION_CREATE_FAILURE = 'TRANSACTION_CREATE_FAILURE';
export const TRANSACTION_CREATE_REQUEST = 'TRANSACTION_CREATE_REQUEST';

export const TRANSACTION_EDIT_REQUEST = 'TRANSACTION_EDIT_REQUEST';
export const TRANSACTION_EDIT_SUCCESS = 'TRANSACTION_EDIT_SUCCESS';
export const TRANSACTION_EDIT_FAILURE = 'TRANSACTION_EDIT_FAILURE';

export const TRANSACTION_DELETE_REQUEST = 'TRANSACTION_DELETE_REQUEST';
export const TRANSACTION_DELETE_SUCCESS = 'TRANSACTION_DELETE_SUCCESS';
export const TRANSACTION_DELETE_FAILURE = 'TRANSACTION_DELETE_FAILURE';

export const TRANSACTION_DETAILS_REQUEST = 'TRANSACTION_DETAILS_REQUEST';
export const TRANSACTION_DETAILS_SUCCESS = 'TRANSACTION_DETAILS_SUCCESS';
export const TRANSACTION_DETAILS_FAILURE = 'TRANSACTION_DETAILS_FAILURE';